# NUMPY
##### My Github:ARSALANnam
##### My Email: arsalannam9710@gmail.com
##### My Linkedin:www.linkedin.com/in/arsalannam

<div style="direction: rtl; text-align: right; font-size: 40px">
NumPy چیست؟
</div>


<div style="direction: rtl; text-align: right; font-size: 20px">
NumPy (مخفف Numerical Python) یک کتابخانه‌ی متن‌باز برای محاسبات عددی با پایتون است. این کتابخانه یک نوع داده‌ی اصلی به نام آرایه‌ی چندبعدی (ndarray) معرفی می‌کند که برای ذخیره و پردازش داده‌های عددی بسیار سریع و کارآمد است.<br>
اگر در پایتون با داده‌های عددی زیاد کار داری، مثل تحلیل داده، هوش مصنوعی، شبیه‌سازی علمی یا حتی پردازش تصویر، یاد گرفتن و استفاده از NumPy تقریباً ضروری هست.
</div>

<div style="direction: rtl; text-align: right; font-size: 30px; color: green">
ویژگی‌های اصلی NumPy
</div>


<div style="direction: rtl; text-align: right; font-size: 20px">
* شیء اصلی ndarray (آرایه‌ی چندبعدی)<br>
* سرعت بالا : NumPy از زبان C استفاده می‌کنه و محاسبات عددی سنگین رو خیلی سریع‌تر از لیست‌های معمولی پایتون انجام می‌ده.<br>
* عملیات برداری (vectorized operations) : به جای استفاده از حلقه‌ها، می‌تونی مستقیماً روی آرایه‌ها عملیات انجام بدی. این کار کد رو کوتاه‌تر و سریع‌تر می‌کنه.<br>
* آرایه‌های چندبعدی : می‌تونی ماتریس‌ها و آرایه‌های 1، 2 یا چندبعدی بسازی و با اون‌ها عملیات ریاضی انجام بدی.<br>
* توابع ریاضی متنوع : جمع، میانگین، انحراف معیار، سینوس، لگاریتم و ...<br>
* پشتیبانی از پخش (broadcasting) : یعنی امکان انجام عملیات بین آرایه‌هایی با ابعاد متفاوت به شکلی هوشمند.
</div>

<div style="direction: rtl; text-align: right; font-size: 30px">
 نصب NumPy
</div>

In [133]:
pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: /home/arsalan/.local/share/pipx/venvs/notebook/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


<div style="direction: rtl; text-align: right; font-size: 30px">
 چگونه NumPy را وارد کنیم؟   
</div>

In [134]:
import numpy as np

<div style="direction: rtl; text-align: right; font-size: 30px">
    مبانی آرایه‌ها (Array Fundamentals)
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
آرایه‌های NumPy هسته‌ی اصلی این کتابخانه هستند. آن‌ها اشیاء ndarray نام دارند.
</div>

In [135]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

<div style="direction: rtl; text-align: right; font-size: 25px">
    ساخت آرایه یک بعدی
</div>

In [136]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

<div style="direction: rtl; text-align: right; font-size: 25px">
    ساخت آرایه دو بعدی
</div>

In [137]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

<div style="direction: rtl; text-align: right; font-size: 20px; color: red">
     نکته: لیست‌های تو در تو باید اندازه‌ی مساوی داشته باشند
</div>

<div style="direction: rtl; text-align: right; font-size: 25px">
    انتخاب نوع داده (dtype)
</div>

In [138]:
np.array([1, 2, 3], dtype=float)


array([1., 2., 3.])

<div style="direction: rtl; text-align: right; font-size: 30px">
ویژگی‌های آرایه در NumPy 
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
وقتی یک آرایه می‌سازیم، NumPy اطلاعات مختلفی درباره‌ی آن نگه می‌دارد. این اطلاعات با ویژگی‌هایی (attributes) مثل .shape, .dtype و ... قابل دسترسی هستند.
</div>

<div style="direction: rtl; text-align: right; font-size: 15px">
تعداد بعد (چندبعدی بودن آرایه)
</div>

In [139]:
a.ndim

2

<div style="direction: rtl; text-align: right; font-size: 15px">
شکل آرایه (تعداد سطر، ستون و ...)	
</div>

In [140]:
a.shape

(2, 3)

<div style="direction: rtl; text-align: right; font-size: 15px">
تعداد کل عناصر آرایه
</div>

In [141]:
a.size

6

<div style="direction: rtl; text-align: right; font-size: 15px">
    نوع داده‌ی عناصر
</div>

In [142]:
a.dtype

dtype('int64')

<div style="direction: rtl; text-align: right; font-size: 15px">
اندازه‌ی هر عنصر بر حسب بایت
</div>

In [143]:
a.itemsize

8

<div style="direction: rtl; text-align: right; font-size: 15px">
    مجموع حافظه‌ی مصرفی (size * itemsize)
</div>

In [144]:
a.nbytes

48

<div style="direction: rtl; text-align: right; font-size: 30px">
    ساخت آرایه‌هایی با مقدار اولیه
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    NumPy توابعی داره برای ساخت آرایه‌هایی با مقدارهای اولیه‌ی مشخص (مثل صفر، یک، یا تصادفی). این کار معمولاً برای ابتدای محاسبات مفیده.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
آرایه‌ای با اندازه‌ی دلخواه که همه‌ی عناصرش صفر هستند:
</div>

In [145]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<div style="direction: rtl; text-align: right; font-size: 20px">
آرایه‌ای با مقدار ۱:
</div>

In [146]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<div style="direction: rtl; text-align: right; font-size: 20px">
آرایه‌ای با اندازه‌ی دلخواه، بدون مقداردهی اولیه. مقادیر تصادفی (باقیمانده‌ی حافظه) خواهد داشت:

</div>

In [147]:
np.empty((2, 2))

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    مثل range() پایتون، ولی خروجی‌اش ndarray است:<br>
    به شکل np.arange(start, stop, step)
</div>

In [148]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

<div style="direction: rtl; text-align: right; font-size: 20px">
    تولید num عدد بین start تا stop به‌طور مساوی:<br>
    به شکل np.linspace(start, stop, num)
</div>

In [149]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

<div style="direction: rtl; text-align: right; font-size: 30px">
    چاپ آرایه‌ها در NumPy

</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
آرایه‌های یک‌بعدی:
</div>

In [150]:
import numpy as np
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


<div style="direction: rtl; text-align: right; font-size: 20px">
     آرایه‌های دوبعدی:
</div>

In [151]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


<div style="direction: rtl; text-align: right; font-size: 20px">
    تابع reshape() به شما این امکان رو می‌ده که آرایه‌ای با شکل (ابعاد) جدید بسازید، به شرطی که تعداد کل عناصر ثابت بماند.
</div>

In [152]:
a = np.arange(6)
b = a.reshape((2, 3))  
print(b)

[[0 1 2]
 [3 4 5]]


<div style="direction: rtl; text-align: right; font-size: 20px; color:red">
نکته: از -1 برای تعیین خودکار بُعد استفاده میشه
</div>

<div style="direction: rtl; text-align: right; font-size: 20px; color:red">
تعداد عناصر قبل و بعد باید برابر باشه.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
     آرایه‌های بزرگ:
</div>

<div style="direction: rtl; text-align: right; font-size: 15px">
    برای آرایه‌های خیلی بزرگ، NumPy فقط قسمت‌هایی از ابتدا و انتها را نشان می‌دهد و وسط را با ... حذف می‌کند:
</div>

In [153]:
c = np.arange(10000)
print(c)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

<div style="direction: rtl; text-align: right; font-size: 20px">
    می‌توان فرمت نمایش را تنظیم کرد:<br>
     این باعث می‌شود کل آرایه چاپ شود (بدون ...).
</div>

In [154]:
np.set_printoptions(threshold=np.inf)

In [155]:
print(c)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

<div style="direction: rtl; text-align: right; font-size: 30px">
     اضافه، حذف و مرتب‌سازی عناصر در NumPy
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    اضافه کردن عناصر np.append()
</div>

In [156]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print(b)

[1 2 3 4 5]


<div style="direction: rtl; text-align: right; font-size: 20px">
     حذف عناصر  np.delete()
</div>

In [157]:
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [1, 3]) 
print(b)

[1 3 5]


In [158]:
a = np.array([[1, 2], [3, 4], [5, 6]])
np.delete(a, 1, axis=0)  # حذف سطر دوم

array([[1, 2],
       [5, 6]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    مرتب‌سازی عناصر  np.sort()
</div>

In [159]:
a = np.array([3, 1, 2])
b = np.sort(a)
print(b)

[1 2 3]


In [160]:
a = np.array([[3, 1], [2, 4]])
np.sort(a, axis=0)  # مرتب‌سازی بر اساس ستون‌ها
np.sort(a, axis=1)  # مرتب‌سازی بر اساس سطرها

array([[1, 3],
       [2, 4]])

<div style="direction: rtl; text-align: right; font-size: 20px; color:red">
    تابع‌هایی مثل append, delete, sort آرایه‌ی جدید برمی‌گردونن و آرایه‌ی اصلی رو تغییر نمی‌دن.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">اتصال آرایه‌ها np.concatenate()<br>
برای چسباندن چند آرایه به هم استفاده می‌شه. همه باید شکل (shape) سازگار داشته باشن.
</div>

In [161]:
a = np.array([1, 2])
b = np.array([3, 4])

c = np.concatenate((a, b))
print(c)  # [1 2 3 4]


[1 2 3 4]


<div style="direction: rtl; text-align: right; font-size: 30px">
    توابع مرتب‌سازی و جستجوی پیشرفته در NumPy
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
     مرتب‌سازی غیرمستقیم:<br>
    به‌جای مرتب‌کردن خود آرایه، اندیس‌هایی برمی‌گردونه که می‌تونن آرایه رو مرتب کنن.
</div>

In [162]:
a = np.array([30, 10, 20])
i = np.argsort(a)
print(i) 
print(a[i]) 

[1 2 0]
[10 20 30]


<div style="direction: rtl; text-align: right; font-size: 20px">
    مرتب‌سازی پایدار با چند کلید (دو یا چند آرایه):<br>
    مثلاً: اول بر اساس نام، بعد بر اساس سن مرتب کن.
</div>

In [163]:
names = np.array(['Arsalan', 'Arsalan', 'Sara'])
ages = np.array([40, 35, 25])

i = np.lexsort((ages, names))
print(i)

[1 0 2]


<div style="direction: rtl; text-align: right; font-size: 20px">
     پیدا کردن جای مناسب یک عدد در آرایه‌ی مرتب‌شده (برای درج کردن):
</div>

In [164]:
a = np.array([20, 30, 40])
i = np.searchsorted(a, 35)
print(i)  # 2 → چون 35 بین 30 و 40 قرار می‌گیره

2


<div style="direction: rtl; text-align: right; font-size: 20px">
 مرتب‌سازی جزئی:<br>
    قط جای یک عنصر خاص (مثلاً کوچک‌ترین سومین عدد) رو پیدا می‌کنه و مطمئن می‌شه که عناصر کوچکتر در سمت چپ هستن.
</div>

In [165]:
a = np.array([7, 2, 5, 1, 9])
p = np.partition(a, 2)
print(p)

[1 2 5 7 9]


<div style="direction: rtl; text-align: right; font-size: 30px">
    Indexing و Slicing در NumPy
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    ایندکس‌گذاری (Indexing)<br>
    مثل لیست‌های پایتون، می‌توانیم با استفاده از اندیس‌ها به عناصر آرایه دسترسی پیدا کنیم.
</div>

In [166]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[2])  

10
30


<div style="direction: rtl; text-align: right; font-size: 20px; color:green">
. اندیس‌ها از صفر شروع می‌شوند.<br>
. می‌توان از اندیس‌های منفی برای دسترسی از انتهای آرایه استفاده کرد.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
ایندکس‌گذاری چند بعدی
    <br>
برای آرایه‌های چندبعدی، از چند عدد اندیس به صورت کاما جدا شده استفاده می‌کنیم:
</div>

In [167]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0, 1])
print(b[1, 2])

2
6


<div style="direction: rtl; text-align: right; font-size: 20px">
 می توانید مقدار شاخص مورد نظر خود را تغییر دهید
</div>

In [168]:
a = np.array([1, 2, 4, 7])
a[1] = 3
a

array([1, 3, 4, 7])

<div style="direction: rtl; text-align: right; font-size: 20px">
    برش (Slicing)<br>
    می‌توان بخش‌هایی از آرایه را با استفاده از برش (slice) برداشت، شبیه به لیست‌های پایتون:
</div>

In [169]:
a = np.array([20, 30, 40, 50, 60, 70 ,80])
print(a[1:4]) 

[30 40 50]


<div style="direction: rtl; text-align: right; font-size: 20px">
    فرمت کلی:<br>
    start: اندیس شروع<br>
stop: اندیسی که تا قبل از آن برش می‌زنیم <br>
step: گام برداشتن (مثلاً هر دو تا یک عنصر)
</div>

<div style="direction: ltr; text-align: left; font-size: 20px">
    array[start:stop:step]

</div>

In [170]:
print(a[::2])  # (هر دو عنصر یک بار)

[20 40 60 80]


<div style="direction: rtl; text-align: right; font-size: 20px">
     برش چند بعدی
</div>

In [171]:
print(b[:, 1])
print(b[0, :]) 

[2 5]
[1 2 3]


<div style="direction: rtl; text-align: right; font-size: 20px; color:red">
    : یعنی همه عناصر در آن بعد.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px; color:red">
    توجه مهم: ایندکس‌ها برش‌ها به آرایه جدید ارجاع نمی‌دهند بلکه نمایشی از همان داده اصلی هستند.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    Iterating (حلقه زدن روی آرایه‌ها)<br>
    می‌توان با for روی آرایه تک بعدی یا چندبعدی حلقه زد:
</div>

In [172]:
for x in a:
    print(x)

20
30
40
50
60
70
80


<div style="direction: rtl; text-align: right; font-size: 20px">
    برای آرایه‌های چندبعدی، هر بار یک ردیف داده می‌شود:
</div>

In [173]:
for row in b:
    print(row)

[1 2 3]
[4 5 6]


<div style="direction: rtl; text-align: right; font-size: 20px">
    اگر بخواهیم روی همه عناصر تک تک حرکت کنیم، از flat استفاده می‌کنیم:
</div>

In [174]:
for element in b.flat:
    print(element)

1
2
3
4
5
6


 <div style="direction: rtl; text-align: right; font-size: 30px">
     چگونه از داده‌های موجود یک آرایه بسازیم
</div>

<div style="direction: rtl; text-align: right; font-size: 25px">
    استفاده از تابع np.array()
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    تابع اصلی برای این کار:
</div>

<div style="direction: ltr; text-align: left; font-size: 20px">
    numpy.array(object)
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    که در آن object می‌تونه لیست یا تاپل یا ترکیبی از آن‌ها باشه.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    لیست یک‌بعدی
</div>

In [175]:
data = [1, 2, 3]
arr = np.array(data)
print(arr)


[1 2 3]


<div style="direction: rtl; text-align: right; font-size: 20px">
     لیست دوبعدی
</div>

In [176]:
data = [[1, 2], [3, 4]]
arr = np.array(data)
print(arr)

[[1 2]
 [3 4]]


<div style="direction: rtl; text-align: right; font-size: 20px">
    تاپل یا ترکیب لیست و تاپل
</div>

In [177]:
data = (1, 2, 3)
arr = np.array(data)
print(arr) 

mixed = [(1, 2), (3, 4)]
arr2 = np.array(mixed)
print(arr2)

[1 2 3]
[[1 2]
 [3 4]]


<div style="direction: rtl; text-align: right; font-size: 30px">
    عملیات پایه‌ای در NumPy
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    وقتی روی آرایه‌ها عمل جمع، ضرب و... انجام می‌دی، NumPy این کار رو عنصری (element-wise) انجام می‌ده؛ یعنی روی تک‌تک عنصرها.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
     جمع، تفریق، ضرب، تقسیم:
</div>

In [180]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b) 
print(a / b) 

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


<div style="direction: rtl; text-align: right; font-size: 20px">
    توابع آماری سریع:
</div>

In [191]:
a = np.array([1, 2, 3, 4])

print(a.sum()) 
print(a.min()) 
print(a.max())   
print(a.mean()) 
print(a.cumsum()) 

10
1
4
2.5
[ 1  3  6 10]


<div style="direction: rtl; text-align: right; font-size: 20px">
     توان و سینوس 
</div>

In [184]:
print(a ** 2)   
print(np.sin(a))        

[1 4 9]
[0.84147098 0.90929743 0.14112001]


<div style="direction: rtl; text-align: right; font-size: 20px">
    ضرب ماتریسی: @ یا dot()
</div>

In [189]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print(A @ B)
print(np.dot(A, B)) # همان بالا

[[ 4  4]
 [10  8]]
[[ 4  4]
 [10  8]]


<div style="direction: rtl; text-align: right; font-size: 20px">
    عملیات روی محور خاص:
</div>

In [183]:
b = np.array([[1, 2], [3, 4]])

b.sum(axis=0)  # جمع ستون‌ها
b.sum(axis=1)  #  جمع سطرها


array([3, 7])

<div style="direction: rtl; text-align: right; font-size: 20px">
    مقایسه:
</div>

In [187]:
a = np.array([1, 2, 4, 5])
b = np.array([3, 3, 4, 6])

print(a > 2) 
print(a == b)  

[False False  True  True]
[False False  True False]


<div style="direction: rtl; text-align: right; font-size: 30px">
     Universal Functions (توابع جهانی یا ufunc)
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    توابعی مثل sin, exp, sqrt, و غیره که روی هر عنصر آرایه به‌صورت مستقل عمل می‌کنن
</div>

In [193]:
a = np.array([1, 2, 3])

<div style="direction: rtl; text-align: right; font-size: 20px">
     تابع سینوس:
</div>

In [194]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

<div style="direction: rtl; text-align: right; font-size: 20px">
    توان:
</div>

In [195]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

<div style="direction: rtl; text-align: right; font-size: 20px">
     جذر:
</div>

In [196]:
np.sqrt(a) 

array([1.        , 1.41421356, 1.73205081])

<div style="direction: rtl; text-align: right; font-size: 20px">
    لگاریتم :
</div>

In [274]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

<div style="direction: rtl; text-align: right; font-size: 20px">
     ویژگی ufunc‌ها:<br>
    - سریع‌تر از حلقه‌های پایتون (زیرساخت C دارند)<br>
    - روی کل آرایه عمل می‌کنن (نیازی به for نیست)<br>
    - قابل ترکیب با هم هستن
</div>

In [197]:
np.sqrt(np.exp(a) + np.sin(a))

array([1.88673072, 2.88068629, 4.49740558])

<div style="direction: rtl; text-align: right; font-size: 30px">
    توابع مهم و پیشرفته NumPy
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
     آمار و ریاضیات پایه
</div>

In [241]:
b = np.array([1, 2, 3, 4])

print(np.sum(b))         # جمع کل عناصر 
print(np.mean(b))        # میانگین
print(np.average(b))     # میانگین
print(np.median(b))      # میانه
print(np.std(b))         # انحراف معیار
print(np.var(b))         # واریانس
print(np.min(b))         # کمینه
print(np.max(b))         # بیشینه
print(np.argmin(b))      # اندیس کمینه
print(np.argmax(b))      # اندیس بیشینه
print(np.clip(b, 2, 3))  # محدود کردن مقدارها به بازه مشخص
print(np.cumsum(b))      # مجموع تجمعی
print(np.cumprod(b))     # حاصل‌ضرب تجمعی
print(np.diff(b))        # اختلاف بین عناصر پشت‌سر‌هم

10
2.5
2.5
2.5
1.118033988749895
1.25
1
4
0
3
[2 2 3 3]
[ 1  3  6 10]
[ 1  2  6 24]
[1 1 1]


<div style="direction: rtl; text-align: right; font-size: 20px">
 توابع منطقی و شرطی
</div>

<div style="direction: rtl; text-align: right; font-size: 18px">
    all : بررسی می‌کنه آیا همه عناصر True هستن
    <br>
    any : بررسی می‌کنه آیا حداقل یک عنصر True هست
    <br>
    where(cond, x, y) : اگر شرط cond برقرار بود، x، وگرنه y
    <br>
    nonzero : اندیس عناصر غیر صفر
</div>

In [204]:
a = np.array([0, 1, 2])

print(np.all(a))   
print(np.any(a))   
print(np.where(a > 0, 10, 0))   
print(np.nonzero(a))  

False
True
[ 0 10 10]
(array([1, 2]),)


<div style="direction: rtl; text-align: right; font-size: 20px">
    مرتب‌سازی و ایندکس
</div>

<div style="direction: rtl; text-align: right; font-size: 15px; color:red">
بالاتر راجبش صحبت کرده بودیم
</div>

In [205]:
c = np.array([3, 1, 2])

print(np.sort(c))   # مرتب‌سازی مستقیم آرایه
print(np.argsort(c))   # مرتب‌سازی غیرمستقیم؛ خروجی: اندیس‌های مرتب‌شده

name = ['ali', 'reza', 'mona']
age = [25, 22, 25]
print(np.lexsort((age, name)))  # مرتب‌سازی پایدار با چند کلید (مثلاً نام + سن)

[1 2 3]
[1 2 0]
[0 2 1]


<div style="direction: rtl; text-align: right; font-size: 20px">
    توابع ماتریسی و برداری
</div>

In [206]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))   # ضرب ماتریسی یا داخلی
print(np.vdot([1, 2], [3, 4]))   # ضرب داخلی (بردارهای ۱بعدی)
print(np.inner([1, 2], [3, 4]))   # ضرب داخلی معمولی
print(np.outer([1, 2], [3, 4]))   # ضرب خارجی (بردار ۱ × بردار ۲)
print(np.cross([1, 0, 0], [0, 1, 0]))   # ضرب برداری (در فضای ۳بعدی)
print(np.trace(A))   # مجموع قطر اصلی ماتریس
print(np.transpose(A))   # ترانهاده: جابجایی سطر و ستون

[[19 22]
 [43 50]]
11
11
[[3 4]
 [6 8]]
[0 0 1]
5
[[1 3]
 [2 4]]


<div style="direction: rtl; text-align: right; font-size: 20px">
    توابع عددی پایه
</div>

In [207]:
d = np.array([1.2, 2.5, 3.8])

print(np.floor(d))   # گرد به پایین
print(np.ceil(d))    # گرد به بالا
print(np.round(d))   # گرد کردن به نزدیک‌ترین عدد صحیح

z = np.array([1+2j, 3+4j])
print(np.real(z))   # قسمت حقیقی عدد مختلط
print(np.conj(z))   # مزدوج مختلط

x = np.array([1, 0, 1])
print(np.invert(x))   # معکوس بیت‌ها (برای بولی یا اعداد صحیح)

[1. 2. 3.]
[2. 3. 4.]
[1. 2. 4.]
[1. 3.]
[1.-2.j 3.-4.j]
[-2 -1 -2]


<div style="direction: rtl; text-align: right; font-size: 20px">
    تحلیل آماری
</div>

In [ ]:
e = np.array([[1, 2], [3, 4]])
f = np.array([[1, 3], [2, 4]])

print(np.corrcoef(e[0], e[1]))   # ضریب همبستگی
print(np.cov(f))                 # ماتریس کوواریانس

<div style="direction: rtl; text-align: right; font-size: 20px">
توابع پیشرفته و قابل سفارشی‌سازی
</div>

In [208]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# اجرای تابع func روی هر سطر یا ستون
print(np.apply_along_axis(np.sum, axis=1, arr=arr)) 

[ 6 15]


In [ ]:
# تبدیل یک تابع ساده پایتون به تابعی که روی آرایه‌ها کار کنه
def square(x): return x * x
vec_square = np.vectorize(square)
print(vec_square(np.array([1, 2, 3])))  # [1 4 9]

<div style="direction: rtl; text-align: right; font-size: 30px">
    ماتریس‌های خاص
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    ماتریس واحد (قطری):
</div>

In [209]:
np.eye(3)   # ماتریس همانی ۳×۳

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    ساخت ماتریس با np.full:
</div>

In [210]:
np.full((2, 3), 7)   # ماتریس ۲×۳ پرشده با ۷

array([[7, 7, 7],
       [7, 7, 7]])

In [223]:
# ماتریس واحد با مقدار دلخواه
np.full((3, 3), fill_value=99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    ماتریس از بازه عددی:
</div>

In [211]:
np.arange(1, 7).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    ماتریس مثلثی بالا و پایین
</div>

In [217]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# مثلثی بالا (بالای قطر اصلی نگه می‌مونه)
print("A1 :",np.triu(A))

# مثلثی پایین (پایین قطر اصلی نگه می‌مونه)
print("A2 :", np.tril(A))


A1 : [[1 2 3]
 [0 5 6]
 [0 0 9]]
A2 : [[1 0 0]
 [4 5 0]
 [7 8 9]]


<div style="direction: rtl; text-align: right; font-size: 20px">
    ماتریس قطری (از یک لیست)
</div>

In [218]:
np.diag([10, 20, 30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

<div style="direction: rtl; text-align: right; font-size: 20px">
ماتریس چرخشی (rotation matrix)
</div>

In [220]:
#  مثلاً در فضای دوبعدی
theta = np.pi / 4  # زاویه ۴۵ درجه
R = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta),  np.cos(theta)]
])

print(R)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


<div style="direction: rtl; text-align: right; font-size: 20px">
    ماتریس تکرارشونده (np.tile)
</div>

In [221]:
a = np.array([[1, 2]])
np.tile(a, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    ماتریس همانی n×n
</div>

In [222]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    ماتریس‌های تصادفی (برای یادگیری ماشین)
</div>

In [225]:
np.random.rand(3, 3)  # بین ۰ و ۱

array([[0.77919462, 0.88117965, 0.03055673],
       [0.97062254, 0.17999121, 0.88884687],
       [0.95951471, 0.26003511, 0.29167129]])

In [226]:
np.random.randint(0, 10, (3, 3))  # اعداد صحیح بین ۰ تا ۹

array([[6, 8, 3],
       [1, 3, 7],
       [8, 0, 7]])

<div style="direction: rtl; text-align: right; font-size: 30px">
    روش‌های مختلف برای تولید اعداد تصادفی
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    اول باید ماژول زیر را  وارد کنید :
</div>

In [227]:
import numpy as np
rng = np.random.default_rng()  # سازنده تولیدکننده عدد تصادفی جدید

<div style="direction: rtl; text-align: right; font-size: 20px">
    اعداد شناور تصادفی بین ۰ تا ۱
</div>

In [232]:
print(rng.random())           # یک عدد تصادفی بین 0 و 1
print(rng.random(5))          # آرایه ۱ بعدی با ۵ عدد
print(rng.random((2, 3)))    # آرایه ۲×۳

0.24175187646806928
[0.18330183 0.0915976  0.38472482 0.61630176 0.20855135]
[[0.5314514  0.73038305 0.55329989]
 [0.73942169 0.54725386 0.20821557]]


<div style="direction: rtl; text-align: right; font-size: 20px">
    اعداد صحیح تصادفی
</div>

In [231]:
print(rng.integers(1, 10))            # یک عدد صحیح بین 1 تا 9
print(rng.integers(1, 10, size=5))    # ۵ عدد صحیح
print(rng.integers(1, 10, size=(2,3)))  # ماتریس ۲×۳ از عدد صحیح

9
[3 7 2 6 1]
[[9 8 6]
 [1 4 7]]


<div style="direction: rtl; text-align: right; font-size: 20px">
    توزیع نرمال (Gaussian)
</div>

In [233]:
rng.normal(loc=0, scale=1, size=5)  # میانگین=0، انحراف معیار=1


array([-0.189937  , -1.36971778, -0.45852468,  0.58950365,  1.86005539])

<div style="direction: rtl; text-align: right; font-size: 20px">
توزیع گسسته (انتخاب تصادفی از لیست)
</div>

In [234]:
rng.choice([10, 20, 30], size=5)     # انتخاب ۵ عدد از این لیست


array([20, 30, 10, 30, 20])

<div style="direction: rtl; text-align: right; font-size: 20px">
   درهم‌ریزی (shuffle)
</div>

In [235]:
arr = np.array([1, 2, 3, 4])
rng.shuffle(arr)
print(arr)  # ترتیبش تصادفی می‌شه

[3 4 2 1]


<div style="direction: rtl; text-align: right; font-size: 20px">
    نمونه‌گیری تصادفی
</div>

In [236]:
rng.permutation(5)   # آرایه‌ی تصادفی شامل اعداد 0 تا 4 به صورت مرتب‌نشده

array([2, 3, 0, 4, 1])

<div style="direction: rtl; text-align: right; font-size: 20px; color:red">
    default_rng() برای تولید عدد تصادفی جدیدتر و امن‌تر از np.random قدیمی استفاده می‌شه.
</div>

<div style="direction: rtl; text-align: right; font-size: 30px">
تغییر شکل پیشرفته آرایه ها
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
     تغییر ابعاد بدون تغییر داده‌ها
</div>

In [237]:
a = np.arange(6) 
b = a.reshape((2, 3))
print(b)

[[0 1 2]
 [3 4 5]]


<div style="direction: rtl; text-align: right; font-size: 20px">
     صاف کردن (یک‌بعدی کردن)
</div>

In [238]:
a = np.array([[1, 2], [3, 4]])
print(a.ravel())

[1 2 3 4]


<div style="direction: rtl; text-align: right; font-size: 20px">
    (transpose)  جابجایی سطر و ستون
</div>

In [239]:
a = np.array([[1, 2], [3, 4]])
print(a.T) 

[[1 3]
 [2 4]]


<div style="direction: rtl; text-align: right; font-size: 20px">
     تغییر اندازه با تغییر در داده‌ها (می‌تونه حذف یا تکرار کنه)
</div>

In [240]:
a = np.array([1, 2, 3])
a.resize((2, 2))
print(a)

[[1 2]
 [3 0]]


<div style="direction: rtl; text-align: right; font-size: 30px">
</div>

<div style="direction: rtl; text-align: right; font-size: 25px">
    تفاوت ravel و flatten
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    ravel() — سریع، ولی نمایی (view)
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    در واقع روی همون آرایه اصلی عملیات رو انجام میده
</div>

In [243]:
a = np.array([[1, 2], [3, 4]])
b = a.ravel()

b[0] = 99
print(a)

[[99  2]
 [ 3  4]]


<div style="direction: rtl; text-align: right; font-size: 25px">
    flatten() — کپی کامل
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    روی آرایه اصلی تغییری ایجاد نمیکنه و یک آرایه مستقل از اون کپی میکنه
</div>

In [244]:
a = np.array([[1, 2], [3, 4]])
b = a.flatten()

b[0] = 99
print(a)

[[1 2]
 [3 4]]


<div style="direction: rtl; text-align: right; font-size: 30px">
    چطور یک آرایه NumPy رو برعکس (reverse) کنیم
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
     برعکس کردن آرایه ۱‌بعدی
</div>

In [245]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
reversed_a = a[::-1]
print(reversed_a)


[5 4 3 2 1]


<div style="direction: rtl; text-align: right; font-size: 25px">
    برعکس کردن سطرها یا ستون‌های آرایه ۲‌بعدی
</div>

In [246]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    برعکس کردن ترتیب سطرها (محور ۰):
</div>

In [247]:
b[::-1, :]

array([[4, 5, 6],
       [1, 2, 3]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    برعکس کردن ترتیب ستون‌ها (محور ۱):
</div>

In [248]:
b[:, ::-1]

array([[3, 2, 1],
       [6, 5, 4]])

<div style="direction: rtl; text-align: right; font-size: 20px">
     برعکس کردن همزمان سطر و ستون:
</div>

In [249]:
b[::-1, ::-1]


array([[6, 5, 4],
       [3, 2, 1]])

<div style="direction: rtl; text-align: right; font-size: 30px">
    روش‌های مختلف اتصال (stack کردن) آرایه‌ها
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
   چسباندن عمودی (محور ۰)
</div>

In [252]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [253]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

<div style="direction: rtl; text-align: right; font-size: 20px">
     چسباندن افقی (محور ۱)
</div>

In [254]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

<div style="direction: rtl; text-align: right; font-size: 20px">
     ترکیب دو آرایه به‌صورت ستون
</div>

In [255]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

<div style="direction: rtl; text-align: right; font-size: 20px">
    اتصال با محور دلخواه
</div>

In [258]:
np.stack((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [259]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

<div style="direction: rtl; text-align: right; font-size: 30px">
    چطور یک آرایه را به چند بخش کوچکتر تقسیم کنیم
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
     تقسیم افقی (ستون‌ها)
</div>

In [260]:
a = np.arange(12).reshape(2, 6)
np.hsplit(a, 3)

[array([[0, 1],
        [6, 7]]),
 array([[2, 3],
        [8, 9]]),
 array([[ 4,  5],
        [10, 11]])]

<div style="direction: rtl; text-align: right; font-size: 20px">
     تقسیم عمودی (سطرها)
</div>

In [261]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

<div style="direction: rtl; text-align: right; font-size: 20px">
    تقسیم به تعداد دلخواه (حتی اگه برابر نشه)
</div>

In [262]:
b = np.arange(10)
np.array_split(b, 3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

<div style="direction: rtl; text-align: right; font-size: 20px">
    تقسیم معمولی ولی باید اندازه‌ها دقیق باشه
</div>

In [263]:
c = np.arange(8)
np.split(c, 4)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]

<div style="direction: rtl; text-align: right; font-size: 30px">
    Copies and views
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    در NumPy، مفاهیم Copy (کپی) و View (نمای داده) بسیار مهم هستند چون در عملکرد، مصرف حافظه و تغییرات روی آرایه‌ها تأثیر مستقیم دارند.
</div

<div style="direction: rtl; text-align: right; font-size: 25px">
    Copy (کپی عمیق)
</div

<div style="direction: rtl; text-align: right; font-size: 20px">
    با استفاده از np.copy() یا .copy() یک نسخه‌ی کاملاً جدا از داده‌ها ایجاد می‌کنی.
</div

In [264]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a) 
print(b)  

[1 2 3]
[100   2   3]


<div style="direction: rtl; text-align: right; font-size: 25px">
    View (کپی سطحی)
</div

<div style="direction: rtl; text-align: right; font-size: 20px">
    View فقط یک اشاره به داده‌های اصلی است. با تغییر آن، آرایه‌ی اصلی هم تغییر می‌کند.
</div

In [265]:
a = np.array([1, 2, 3])
b = a.view()
b[0] = 100

print(a)

[100   2   3]


<div style="direction: rtl; text-align: right; font-size: 20px">
    بررسی اینکه آیا b یک view از a هست یا نه؟

</div>

In [266]:
b.base is a 

True

<div style="direction: rtl; text-align: right; font-size: 30px">
    Boolean Indexing 
</div

<div style="direction: rtl; text-align: right; font-size: 20px">
وقتی بخواهی فقط عناصری از آرایه را انتخاب کنی که شرط خاصی را دارند، از Boolean Indexing استفاده می‌کنی.
NumPy به جای دادن ایندکس عددی، یک آرایه بولی (True/False) به عنوان ماسک استفاده می‌کند.
</div>

In [267]:
a = np.array([10, 20, 30, 40, 50])
mask = a > 25 
print(mask)

filtered = a[mask]
print(filtered)  

[False False  True  True  True]
[30 40 50]


<div style="direction: rtl; text-align: right; font-size: 20px">
    mask یک آرایه از True و False است، به طول آرایه اصلی.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    حالت مستقیم:
</div>

In [273]:
print(a[a % 20 == 0]) 

[20 40]


<div style="direction: rtl; text-align: right; font-size: 20px">
    کاربردهای رایج:
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
   - انتخاب عناصر بزرگ‌تر یا کوچک‌تر از عددی خاص و عناصر زوج یا فرد
    <br>
   - ترکیب چند شرط با & (و) یا | (یا)
</div>

In [271]:
print(a[(a > 20) & (a < 40)]) 

[30]


<div style="direction: rtl; text-align: right; font-size: 30px">
    روش‌های ذخیره و بارگذاری آرایه‌های NumPy
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    ذخیره آرایه
</div>

In [276]:
a = np.array([1, 2, 3, 4, 5])
np.save('my_array.npy', a) #    ذخیره آرایه در فایلی به اسم my_array.npy

<div style="direction: rtl; text-align: right; font-size: 20px">
    ذخیره چند آرایه
</div>

In [277]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.savez('arrays.npz', array1=a, array2=b)

<div style="direction: rtl; text-align: right; font-size: 20px">
    بارگذاری آرایه
</div>

In [278]:
b = np.load('my_array.npy')
print(b) 

[1 2 3 4 5]


<div style="direction: rtl; text-align: right; font-size: 20px">
    بارگذاری چند آرایه از فایل
</div>

In [279]:
data = np.load('arrays.npz')
print(data['array1']) 
print(data['array2'])  

[1 2 3]
[4 5 6]


<div style="direction: rtl; text-align: right; font-size: 30px">
     خواندن و نوشتن فایل‌های CSV
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    خواندن CSV ساده
    <br>
        مناسب وقتی فایل فقط عددی است و بدون هدر.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
     خواندن CSV با هدر و داده‌های ناقص
    <br>
    مناسب برای داده‌های پیچیده‌تر یا وجود داده‌های خالی.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    نوشتن آرایه به CSV
</div>

<div style="direction: rtl; text-align: right; font-size: 30px">
    نکات مهم
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
    - NumPy بیشتر برای داده‌های عددی مناسبه.
    <br>
    - برای داده‌های ترکیبی (اعداد و رشته) بهتر  از pandas استفاده کنی.
    <br>
    - خواندن و نوشتن CSV در NumPy سریع و ساده است ولی امکانات محدودتری نسبت به pandas داره.
</div>

<div style="direction: rtl; text-align: right; font-size: 20px">
💢 امیدوارم که این Notebook مفید بوده باشه و بتونه به شما در یادگیری NumPy کمک کنه.سعی کردم تمام نکات و بخش های مهم NumPy رو براتون یکجا جمع کنم تا راحت به یادگیری بپردازیم ;)
    <br>
اگر سوالی و نکته ای بود میتونید با من از طریق ایمیل و یا تلگرام در ارتباط باشید.رفیق شما ارسلانم.
    <br>
    <br>
ما هنوز باور داریم به خدای رنگین کمان 💫🌈
</div>